swagger: '2.0'
info:
  title: MOLOCO Hello-Rest Sample API
  description: This is a sample API for the REST-based MOLOCO microservice development.
  version: 1.0.0
host: api-first-01.example.com
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
x-google-backend:
  address: https://api-first-01.example.com
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
paths:
  /v1/hellos:
    $ref: './api_hello.yaml'

  /v1/hellos/{hello_id}:
    $ref: './api_hello_id.yaml'

  /v1/hellos/{hello_id}/status:
    $ref: './api_hello_id_status.yaml'

  /:
    $ref: './api_health.yaml'
