swagger: '2.0'
definitions:
  Error:
    description: Error response with detailed reason.
    type: object
    properties:
      code:
        description: The error status code.
        type: integer
      message:
        description: More detailed reason about why the error was returned.
        type: string
    required:
      - code
      - message
