// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewV1HealthCheckParams creates a new V1HealthCheckParams object
// no default values defined in spec.
func NewV1HealthCheckParams() V1HealthCheckParams {

	return V1HealthCheckParams{}
}

// V1HealthCheckParams contains all the bound params for the v1 health check operation
// typically these are obtained from a http.Request
//
// swagger:parameters v1_health_check
type V1HealthCheckParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewV1HealthCheckParams() beforehand.
func (o *V1HealthCheckParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
