// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"api-first-01/api/swagger/models"
)

// V1HealthCheckOKCode is the HTTP code returned for type V1HealthCheckOK
const V1HealthCheckOKCode int = 200

/*V1HealthCheckOK The API is working fine.

swagger:response v1HealthCheckOK
*/
type V1HealthCheckOK struct {

	/*
	  In: Body
	*/
	Payload *models.HealthCheckResponse `json:"body,omitempty"`
}

// NewV1HealthCheckOK creates V1HealthCheckOK with default headers values
func NewV1HealthCheckOK() *V1HealthCheckOK {

	return &V1HealthCheckOK{}
}

// WithPayload adds the payload to the v1 health check o k response
func (o *V1HealthCheckOK) WithPayload(payload *models.HealthCheckResponse) *V1HealthCheckOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 health check o k response
func (o *V1HealthCheckOK) SetPayload(payload *models.HealthCheckResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1HealthCheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V1HealthCheckInternalServerErrorCode is the HTTP code returned for type V1HealthCheckInternalServerError
const V1HealthCheckInternalServerErrorCode int = 500

/*V1HealthCheckInternalServerError Internal Server Error.

swagger:response v1HealthCheckInternalServerError
*/
type V1HealthCheckInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV1HealthCheckInternalServerError creates V1HealthCheckInternalServerError with default headers values
func NewV1HealthCheckInternalServerError() *V1HealthCheckInternalServerError {

	return &V1HealthCheckInternalServerError{}
}

// WithPayload adds the payload to the v1 health check internal server error response
func (o *V1HealthCheckInternalServerError) WithPayload(payload *models.Error) *V1HealthCheckInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 health check internal server error response
func (o *V1HealthCheckInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1HealthCheckInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
