// Code generated by mockery v1.0.0. DO NOT EDIT.

package list

import (
	storage "api-first-01/storage"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHelloStorage is an autogenerated mock type for the HelloStorage type
type MockHelloStorage struct {
	mock.Mock
}

// ListHellos provides a mock function with given fields: _a0, _a1
func (_m *MockHelloStorage) ListHellos(_a0 context.Context, _a1 *storage.ListHellosRequest) (*storage.ListHellosResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *storage.ListHellosResponse
	if rf, ok := ret.Get(0).(func(context.Context, *storage.ListHellosRequest) *storage.ListHellosResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ListHellosResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *storage.ListHellosRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
