// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ListHellosResponse A response to the request to list hellos.
//
// swagger:model listHellosResponse
type ListHellosResponse struct {

	// The hellos.
	// Required: true
	Hellos []*Hello `json:"hellos"`
}

// Validate validates this list hellos response
func (m *ListHellosResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHellos(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListHellosResponse) validateHellos(formats strfmt.Registry) error {

	if err := validate.Required("hellos", "body", m.Hellos); err != nil {
		return err
	}

	for i := 0; i < len(m.Hellos); i++ {
		if swag.IsZero(m.Hellos[i]) { // not required
			continue
		}

		if m.Hellos[i] != nil {
			if err := m.Hellos[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("hellos" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListHellosResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListHellosResponse) UnmarshalBinary(b []byte) error {
	var res ListHellosResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
