// Code generated by go-swagger; DO NOT EDIT.

// Package restapi MOLOCO Hello-Rest Sample API
//
//  This is a sample API for the REST-based MOLOCO microservice development.
//  Schemes:
//    https
//  Host: api-first-01.example.com
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
