// Code generated by go-swagger; DO NOT EDIT.

package hello

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// V1CreateHelloHandlerFunc turns a function with the right signature into a v1 create hello handler
type V1CreateHelloHandlerFunc func(V1CreateHelloParams) middleware.Responder

// Handle executing the request and returning a response
func (fn V1CreateHelloHandlerFunc) Handle(params V1CreateHelloParams) middleware.Responder {
	return fn(params)
}

// V1CreateHelloHandler interface for that can handle valid v1 create hello params
type V1CreateHelloHandler interface {
	Handle(V1CreateHelloParams) middleware.Responder
}

// NewV1CreateHello creates a new http.Handler for the v1 create hello operation
func NewV1CreateHello(ctx *middleware.Context, handler V1CreateHelloHandler) *V1CreateHello {
	return &V1CreateHello{Context: ctx, Handler: handler}
}

/*V1CreateHello swagger:route POST /v1/hellos Hello v1CreateHello

Create a Hello.

Create a new hello.

*/
type V1CreateHello struct {
	Context *middleware.Context
	Handler V1CreateHelloHandler
}

func (o *V1CreateHello) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewV1CreateHelloParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
