// Code generated by go-swagger; DO NOT EDIT.

package hello

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"api-first-01/api/swagger/models"
)

// V1ListHellosOKCode is the HTTP code returned for type V1ListHellosOK
const V1ListHellosOKCode int = 200

/*V1ListHellosOK The list of hellos.

swagger:response v1ListHellosOK
*/
type V1ListHellosOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListHellosResponse `json:"body,omitempty"`
}

// NewV1ListHellosOK creates V1ListHellosOK with default headers values
func NewV1ListHellosOK() *V1ListHellosOK {

	return &V1ListHellosOK{}
}

// WithPayload adds the payload to the v1 list hellos o k response
func (o *V1ListHellosOK) WithPayload(payload *models.ListHellosResponse) *V1ListHellosOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 list hellos o k response
func (o *V1ListHellosOK) SetPayload(payload *models.ListHellosResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ListHellosOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V1ListHellosBadRequestCode is the HTTP code returned for type V1ListHellosBadRequest
const V1ListHellosBadRequestCode int = 400

/*V1ListHellosBadRequest Bad request.

swagger:response v1ListHellosBadRequest
*/
type V1ListHellosBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV1ListHellosBadRequest creates V1ListHellosBadRequest with default headers values
func NewV1ListHellosBadRequest() *V1ListHellosBadRequest {

	return &V1ListHellosBadRequest{}
}

// WithPayload adds the payload to the v1 list hellos bad request response
func (o *V1ListHellosBadRequest) WithPayload(payload *models.Error) *V1ListHellosBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 list hellos bad request response
func (o *V1ListHellosBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ListHellosBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V1ListHellosInternalServerErrorCode is the HTTP code returned for type V1ListHellosInternalServerError
const V1ListHellosInternalServerErrorCode int = 500

/*V1ListHellosInternalServerError Internal Server Error.

swagger:response v1ListHellosInternalServerError
*/
type V1ListHellosInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV1ListHellosInternalServerError creates V1ListHellosInternalServerError with default headers values
func NewV1ListHellosInternalServerError() *V1ListHellosInternalServerError {

	return &V1ListHellosInternalServerError{}
}

// WithPayload adds the payload to the v1 list hellos internal server error response
func (o *V1ListHellosInternalServerError) WithPayload(payload *models.Error) *V1ListHellosInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 list hellos internal server error response
func (o *V1ListHellosInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ListHellosInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
