// Code generated by go-swagger; DO NOT EDIT.

package hello

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"api-first-01/api/swagger/models"
)

// V1ReadHelloStatusOKCode is the HTTP code returned for type V1ReadHelloStatusOK
const V1ReadHelloStatusOKCode int = 200

/*V1ReadHelloStatusOK The status of the given hello.

swagger:response v1ReadHelloStatusOK
*/
type V1ReadHelloStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.ReadHelloStatusResponse `json:"body,omitempty"`
}

// NewV1ReadHelloStatusOK creates V1ReadHelloStatusOK with default headers values
func NewV1ReadHelloStatusOK() *V1ReadHelloStatusOK {

	return &V1ReadHelloStatusOK{}
}

// WithPayload adds the payload to the v1 read hello status o k response
func (o *V1ReadHelloStatusOK) WithPayload(payload *models.ReadHelloStatusResponse) *V1ReadHelloStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 read hello status o k response
func (o *V1ReadHelloStatusOK) SetPayload(payload *models.ReadHelloStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ReadHelloStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V1ReadHelloStatusBadRequestCode is the HTTP code returned for type V1ReadHelloStatusBadRequest
const V1ReadHelloStatusBadRequestCode int = 400

/*V1ReadHelloStatusBadRequest Bad request

swagger:response v1ReadHelloStatusBadRequest
*/
type V1ReadHelloStatusBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV1ReadHelloStatusBadRequest creates V1ReadHelloStatusBadRequest with default headers values
func NewV1ReadHelloStatusBadRequest() *V1ReadHelloStatusBadRequest {

	return &V1ReadHelloStatusBadRequest{}
}

// WithPayload adds the payload to the v1 read hello status bad request response
func (o *V1ReadHelloStatusBadRequest) WithPayload(payload *models.Error) *V1ReadHelloStatusBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 read hello status bad request response
func (o *V1ReadHelloStatusBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ReadHelloStatusBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V1ReadHelloStatusNotFoundCode is the HTTP code returned for type V1ReadHelloStatusNotFound
const V1ReadHelloStatusNotFoundCode int = 404

/*V1ReadHelloStatusNotFound Not found

swagger:response v1ReadHelloStatusNotFound
*/
type V1ReadHelloStatusNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV1ReadHelloStatusNotFound creates V1ReadHelloStatusNotFound with default headers values
func NewV1ReadHelloStatusNotFound() *V1ReadHelloStatusNotFound {

	return &V1ReadHelloStatusNotFound{}
}

// WithPayload adds the payload to the v1 read hello status not found response
func (o *V1ReadHelloStatusNotFound) WithPayload(payload *models.Error) *V1ReadHelloStatusNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 read hello status not found response
func (o *V1ReadHelloStatusNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ReadHelloStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V1ReadHelloStatusInternalServerErrorCode is the HTTP code returned for type V1ReadHelloStatusInternalServerError
const V1ReadHelloStatusInternalServerErrorCode int = 500

/*V1ReadHelloStatusInternalServerError Internal Server Error

swagger:response v1ReadHelloStatusInternalServerError
*/
type V1ReadHelloStatusInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV1ReadHelloStatusInternalServerError creates V1ReadHelloStatusInternalServerError with default headers values
func NewV1ReadHelloStatusInternalServerError() *V1ReadHelloStatusInternalServerError {

	return &V1ReadHelloStatusInternalServerError{}
}

// WithPayload adds the payload to the v1 read hello status internal server error response
func (o *V1ReadHelloStatusInternalServerError) WithPayload(payload *models.Error) *V1ReadHelloStatusInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 read hello status internal server error response
func (o *V1ReadHelloStatusInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ReadHelloStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
