// Code generated by go-swagger; DO NOT EDIT.

package hello

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewV1ReadHelloParams creates a new V1ReadHelloParams object
// no default values defined in spec.
func NewV1ReadHelloParams() V1ReadHelloParams {

	return V1ReadHelloParams{}
}

// V1ReadHelloParams contains all the bound params for the v1 read hello operation
// typically these are obtained from a http.Request
//
// swagger:parameters v1_read_hello
type V1ReadHelloParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The ID of the hello.
	  Required: true
	  In: path
	*/
	HelloID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewV1ReadHelloParams() beforehand.
func (o *V1ReadHelloParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rHelloID, rhkHelloID, _ := route.Params.GetOK("hello_id")
	if err := o.bindHelloID(rHelloID, rhkHelloID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindHelloID binds and validates parameter HelloID from path.
func (o *V1ReadHelloParams) bindHelloID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.HelloID = raw

	return nil
}
