// Code generated by go-swagger; DO NOT EDIT.

package hello

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"api-first-01/api/swagger/models"
)

// V1ReadHelloOKCode is the HTTP code returned for type V1ReadHelloOK
const V1ReadHelloOKCode int = 200

/*V1ReadHelloOK The hello is successfully read.

swagger:response v1ReadHelloOK
*/
type V1ReadHelloOK struct {

	/*
	  In: Body
	*/
	Payload *models.ReadHelloResponse `json:"body,omitempty"`
}

// NewV1ReadHelloOK creates V1ReadHelloOK with default headers values
func NewV1ReadHelloOK() *V1ReadHelloOK {

	return &V1ReadHelloOK{}
}

// WithPayload adds the payload to the v1 read hello o k response
func (o *V1ReadHelloOK) WithPayload(payload *models.ReadHelloResponse) *V1ReadHelloOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 read hello o k response
func (o *V1ReadHelloOK) SetPayload(payload *models.ReadHelloResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ReadHelloOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V1ReadHelloBadRequestCode is the HTTP code returned for type V1ReadHelloBadRequest
const V1ReadHelloBadRequestCode int = 400

/*V1ReadHelloBadRequest Bad request

swagger:response v1ReadHelloBadRequest
*/
type V1ReadHelloBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV1ReadHelloBadRequest creates V1ReadHelloBadRequest with default headers values
func NewV1ReadHelloBadRequest() *V1ReadHelloBadRequest {

	return &V1ReadHelloBadRequest{}
}

// WithPayload adds the payload to the v1 read hello bad request response
func (o *V1ReadHelloBadRequest) WithPayload(payload *models.Error) *V1ReadHelloBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 read hello bad request response
func (o *V1ReadHelloBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ReadHelloBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V1ReadHelloNotFoundCode is the HTTP code returned for type V1ReadHelloNotFound
const V1ReadHelloNotFoundCode int = 404

/*V1ReadHelloNotFound Not found - no such user.

swagger:response v1ReadHelloNotFound
*/
type V1ReadHelloNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV1ReadHelloNotFound creates V1ReadHelloNotFound with default headers values
func NewV1ReadHelloNotFound() *V1ReadHelloNotFound {

	return &V1ReadHelloNotFound{}
}

// WithPayload adds the payload to the v1 read hello not found response
func (o *V1ReadHelloNotFound) WithPayload(payload *models.Error) *V1ReadHelloNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 read hello not found response
func (o *V1ReadHelloNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ReadHelloNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V1ReadHelloInternalServerErrorCode is the HTTP code returned for type V1ReadHelloInternalServerError
const V1ReadHelloInternalServerErrorCode int = 500

/*V1ReadHelloInternalServerError Internal Server Error

swagger:response v1ReadHelloInternalServerError
*/
type V1ReadHelloInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV1ReadHelloInternalServerError creates V1ReadHelloInternalServerError with default headers values
func NewV1ReadHelloInternalServerError() *V1ReadHelloInternalServerError {

	return &V1ReadHelloInternalServerError{}
}

// WithPayload adds the payload to the v1 read hello internal server error response
func (o *V1ReadHelloInternalServerError) WithPayload(payload *models.Error) *V1ReadHelloInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v1 read hello internal server error response
func (o *V1ReadHelloInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V1ReadHelloInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
